---
deployment:
  tasks:
    - export DEPLOYPATH=/home/edwins27/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH